### ISSUE TITLE
Generation uses Hibernate - how can I force EclipseLink

### ISSUE THREAD

**Issue by gdelprete** [divinespear/jpa-schema-gradle-plugin#15]
Hi,

I'm using EclipseLink in my project (version 2.5.3) but the Gradle plugin is using Hibernate to generate the DDL. How can I force the plugin to use EclipseLink's generator?

**Comment by divinespear** [comment]
Please put your `persistence.xml`.
BTW, provider will use defined in `persistence.xml`.

**Comment by divinespear** [comment]
not responding, closing issue.

**Comment by gdelprete** [comment]
Sorry, got busy with other issues.

This is my persistence XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence 
	version="2.1" 
	xmlns="http://xmlns.jcp.org/xml/ns/persistence" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
	
	<persistence-unit name="default">
 		<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
		<class>com.app.web.model.jpa.NewsItemPK</class>
		<class>com.app.web.model.jpa.NewsItem</class>
		<class>com.app.web.model.jpa.BinaryContentNewsItem</class>
		<class>com.app.web.model.jpa.TextContentNewsItem</class>
		<class>com.app.web.model.jpa.Category</class>
		<class>com.app.web.model.jpa.eclipselink.DateTimeJPA21Converter</class>
		<exclude-unlisted-classes>true</exclude-unlisted-classes>
		<properties>
 			<property name="eclipselink.weaving" value="static"/>
 			<property name="eclipselink.logging.logger" value="com.app.web.model.jpa.eclipselink.SLF4JLogger"/>
			<property name="eclipselink.logging.level" value="finest"/>
		</properties>
	</persistence-unit>
</persistence>
```

The config in gradle is:

```gradle
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath "io.github.divinespear:jpa-schema-gradle-plugin:0.1.12"
	}
}

apply plugin: "jpa-schema-generate"

generateSchema {
	databaseProductName = "MySQL"
	scriptAction = "drop-and-create"
	format = true
	persistenceXml = file("src/main/resources/META-INF/persistence.xml")
}


```

When I run generateSchema I get this result, quoting Hibernate and saying that a Persistence Provider can't be found:

```

sts] -----------------------------------------------------
[sts] Starting Gradle build for the following tasks: 
[sts]      clean
[sts]      generateSchema
[sts] -----------------------------------------------------
:news-nx-scrollers2-common:clean
:news-nx-scrollers2-common:compileJava
:news-nx-scrollers2-common:processResources
:news-nx-scrollers2-common:classes
:news-nx-scrollers2-common:weave
:news-nx-scrollers2-common:generateSchema
HHH015016: Encountered a deprecated javax.persistence.spi.PersistenceProvider [org.hibernate.ejb.HibernatePersistence]; use [org.hibernate.jpa.HibernatePersistenceProvider] instead.
HHH015016: Encountered a deprecated javax.persistence.spi.PersistenceProvider [org.hibernate.ejb.HibernatePersistence]; use [org.hibernate.jpa.HibernatePersistenceProvider] instead.
HHH015016: Encountered a deprecated javax.persistence.spi.PersistenceProvider [org.hibernate.ejb.HibernatePersistence]; use [org.hibernate.jpa.HibernatePersistenceProvider] instead.
:news-nx-scrollers2-common:generateSchema FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':news-nx-scrollers2-common:generateSchema'.
> No Persistence provider to generate schema named default

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.397 secs
[sts] Build failed
org.gradle.tooling.BuildException: Could not execute build using Gradle installation '/opt/gradle-2.2.1'.

...
...

Caused by: javax.persistence.PersistenceException: No Persistence provider to generate schema named default
	at io.github.divinespear.JpaSchemaGenerateTask$_generate_closure9.doCall(JpaSchemaGenerateTask.groovy:301)
	at io.github.divinespear.JpaSchemaGenerateTask.generate(JpaSchemaGenerateTask.groovy:284)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 55 more
```

**Comment by divinespear** [comment]
You can ignore persistenceXml option if your persistence xml path is `META-INF/persistence.xml`
remove it and retry please.

**Comment by divinespear** [comment]
... any luck?

**Comment by gdelprete** [comment]
Yes, now it works.

I have a suggestion though: please add a log line thatn states the
persistence engine the plugin selected in the end. This way it is always
clear which Persistence Provider is generating your DDL.

Thanks!

2015-02-24 19:59 GMT-05:00 divinespear <notifications@github.com>:
