### ISSUE TITLE
java.io.NotSerializableException after migration from 0.2.1-1 to 0.3.5.1

### ISSUE THREAD

**Issue by ragnor** [divinespear/jpa-schema-gradle-plugin#38]
Hi,
I've migrated my project from 0.2.1-1 to 0.3.5.1 but after applying all required changes below error occurs:
```
Task :generateSchema FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Unable to store input properties for task ':generateSchema'. Property 'extension' with value 'io.github.divinespear.plugin.JpaSchemaGenerationExtension_Decorated@7746850b' cannot be serializ
ed.
> java.io.NotSerializableException: io.github.divinespear.plugin.JpaSchemaGenerationExtension_Decorated

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.UncheckedIOException: Unable to store input properties for task ':generateSchema'. Property 'extension' with value 'io.github.divinespear.plugin.JpaSchemaGenerationExtension_D
ecorated@7746850b' cannot be serialized.
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.snapshotTaskInputProperties(CacheBackedTaskHistoryRepository.java:319)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.createExecution(CacheBackedTaskHistoryRepository.java:151)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.access$100(CacheBackedTaskHistoryRepository.java:66)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.getCurrentExecution(CacheBackedTaskHistoryRepository.java:116)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:208)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:93)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:50)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.io.NotSerializableException: io.github.divinespear.plugin.JpaSchemaGenerationExtension_Decorated
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.serialize(ValueSnapshotter.java:185)
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.processValue(ValueSnapshotter.java:174)
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.snapshot(ValueSnapshotter.java:64)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.snapshotTaskInputProperties(CacheBackedTaskHistoryRepository.java:314)
        ... 32 more
Caused by: java.io.NotSerializableException: io.github.divinespear.plugin.JpaSchemaGenerationExtension_Decorated
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.serialize(ValueSnapshotter.java:182)
        ... 35 more
```
The application is based on spring-boot 2.0.3.RELEASE, build is executed on gradle 4.7 and 1.8.0_171 (64 bit).
Generate schema task is configured as below:
```
generateSchema {
   // this is only change in the task between 0.2.1-1 and 0.3.5.1
    vendor = 'hibernate+spring' 
    databaseProductName = 'MySQL'
    databaseMajorVersion = 5
    databaseMinorVersion = 7
    databaseAction = 'none'
    scriptAction = 'create'
    format = true
    jdbcDriver = 'com.mysql.jdbc.Driver'
    outputDirectory = file("${project.buildDir}/resources/main/META-INF/database/sql")
    createOutputFileName = 'initial-create.sql'
    packageToScan = ['com.test.model']
    properties = [
            'hibernate.dialect': 'org.hibernate.dialect.MySQL57InnoDBDialect'
    ]
}
```
I'm open to any advice or workaround that will help to solve the issue.

**Comment by ragnor** [comment]
Any plans to solve the issue?

**Comment by ragnor** [comment]
I've made it work, the reason of the issue was my optimization to the task:
```
tasks.getByName('generateSchema').getInputs().dir(file("${project.buildDir}/classes/java/main"))
tasks.getByName('generateSchema').getOutputs().dirs(file("${project.buildDir}/database/sql"))
```
