### ISSUE TITLE
Generate schema task throws kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by gpmind** [divinespear/jpa-schema-gradle-plugin#40]
This plugin just throws kotlin.KotlinNullPointerException on basically nothing with a standard bare bone java-library deployment.

```
plugins {
    id 'io.github.divinespear.jpa-schema-generate' version '0.3.5.1'
}

apply plugin: 'java-library'
apply plugin: 'io.github.divinespear.jpa-schema-generate'
```

...

```
generateSchema {
    targets {
        targetName {
        }
    }
}
```

./gradlew generateSchema -> kotlin.KotlinNullPointerException

I would expect a significant error message if any configuration is missing anywhere. I have a persistence.xml file in the right path and don't need to scan packages.

Gradle wrapper is set on 4.4.1

**Comment by ghilainm** [comment]
I have exactly the same issue.

My config is:

- vendor = 'hibernate+spring'
- three package to scan

Nothing more.

**Comment by ghilainm** [comment]
Okay the answer is to specify the following parameter:

    databaseProductName = <your database name> (e.g. PostgreSQL)

Should be added to documentation. 

By the way the documentation should be updated to reference all the possible options.

**Comment by ivarprudnikov** [comment]
There are more details when running with `--stacktrace` option:

```
...
Caused by: kotlin.KotlinNullPointerException
        at io.github.divinespear.plugin.TaskKt.persistenceProperties(task.kt:238)
        at io.github.divinespear.plugin.TaskKt.access$persistenceProperties(task.kt:1)
        at io.github.divinespear.plugin.JpaSchemaGenerationTask.doGenerate(task.kt:123)
        at io.github.divinespear.plugin.JpaSchemaGenerationTask.doRun(task.kt:84)
        at io.github.divinespear.plugin.JpaSchemaGenerationTask.run(task.kt:50)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        ....
```

**Comment by divinespear** [comment]
@ivarprudnikov Sorry about too late response, I've heavy work loads...
You need to set `databaseProductName` options if did not set `hibernate.dialect` on `properties`.

**Comment by spyro2000** [comment]
Did set properties = mapOf("hibernate.dialect" to "org.hibernate.dialect.MySQL5InnoDBDialect")` but still getting a NPE
